default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['SUPABASE_HOST'] %>
  port: <%= ENV['SUPABASE_PORT'] %>
  username: <%= ENV['SUPABASE_USERNAME'] %>
  password: <%= ENV['SUPABASE_PASSWORD'] %>
  database: <%= ENV['SUPABASE_DATABASE'] %>
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
